version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/eth_deposit_tracker
      - INFURA_WS_URL=wss://mainnet.infura.io/ws/v3/7b56140f16d64ca995cf6c50a84b39c4
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - ethereum_tracker_network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ethereum_tracker_network

volumes:
  mongo-data:

networks:
  ethereum_tracker_network:
    driver: bridge
